-- =============================================
-- tracks 테이블 수정 (Supabase SQL Editor에서 실행)
-- 1. youtube_link 컬럼 추가
-- 2. id 컬럼을 CSV import 가능하도록 변경
-- =============================================

-- 1. youtube_link 컬럼 추가
alter table tracks add column if not exists youtube_link text;

-- 2. id를 generated by default로 변경 (CSV의 id값 그대로 import 가능)
alter table tracks alter column id set generated by default;
